добавил работу с ресташуром через базовый класс
ylptred/RestAssuredSandbox pull request #1
Opened 2024-01-20 20:20 UTC by ylptred

2024-01-21 08:21 UTC, ryba1kin commented on src/main/java/org/example/utils/http/HttpClient.java
> +                .all()
логирование лучше вытаскивать в статичную инициализацию рест ашурда:
`RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter())`

2024-01-21 08:21 UTC, ryba1kin commented on src/main/java/org/example/utils/http/HttpClient.java
> +                .basePath(attributes.basePath)
basePath нужен не совсем для этого, лучше использовать путь к конечной точке - передавая аргументом в `get(attributes.basePath)` или прочие вызовы (get post put patch и прочие являются триггерным методом, в момент исполнения которого и происходит запрос)

2024-01-21 08:21 UTC, ryba1kin commented on src/main/java/org/example/utils/http/HttpClient.java
> +    public Response postRequest() {
вот эту пару можно обьединить в реализации (если нет прочих условий):
 попробуй сам выделить общий логический кусок (в `postRequest` и `putRequest`) и вынести его приватным методом

2024-01-21 08:21 UTC, ryba1kin commented on src/main/java/org/example/utils/http/HttpClient.java
> +                .all()
надо делать синглтон класс с инициализацией или в статик блок любого класса:
статик блок:
```
class ImyaClassa {
    static{
        RestAssured....
    }
}
```

2024-01-21 08:21 UTC, ryba1kin commented on src/test/java/test/megamarket/MainPageTest.java
> +    @Test(description = "Проверяем доступность сервиса СберМегаМаркет")
тут гуд по использованию

2024-01-21 08:30 UTC, ryba1kin requested changes

2024-01-21 08:30 UTC, ryba1kin commented on src/main/java/org/example/utils/config/Props.java
> +        File configFile = new File("src/test/java/resources/config/config.properties");
Две строки с чтением файла лучше делать с `java.nio`пакетом, статичный метод 
```java
Files.newInputStream(Paths.get("src/test/java/resources/config/config.properties"), StandardOpenOption.READ);
```
Потому что меньше вероятность ошибок, и делается небллокирующее открытие файла на чтение

2024-01-21 09:35 UTC, ylptred commented on src/main/java/org/example/utils/http/HttpClient.java
> +    public Response postRequest() {
вообще можно из всех трех методов выделить часть в приватку, закину это в ближайший коммит

2024-01-22 10:12 UTC, ryba1kin approved these changes

2024-01-22 10:15 UTC, ryba1kin approved these changes

2024-01-22 10:15 UTC, ryba1kin commented on src/test/java/test/megamarket/MainPageTest.java
>                  .log()
лог то убери в конце концов, настроено же =)

2024-01-22 20:06 UTC, merged